---
sudo: false
language: ruby
cache: bundler
addons:
  postgresql: "9.6"
rvm:
  # TODO fix build set up
  # - 2.0.0-p648
  # - 2.1.10
  # - 2.2.6
  - 2.3.7
  - 2.4.2
  - 2.5.1
  - 2.6.3
  - ruby-head
  - jruby-9.1.9.0
  - jruby-9.2.5.0
  - jruby-head
gemfile:
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.2.gemfile
  - gemfiles/activerecord_6.0rc1.gemfile
env:
  - DB=sqlite
  - DB=postgres

matrix:
  fast_finish: true
  exclude:
  - rvm: 2.2.6
    gemfile: gemfiles/activerecord_6.0rc1.gemfile
  - rvm: 2.3.5
    gemfile: gemfiles/activerecord_6.0rc1.gemfile
  - rvm: 2.4.2
    gemfile: gemfiles/activerecord_6.0rc1.gemfile
  - rvm: jruby-9.1.9.0
    gemfile: gemfiles/activerecord_5.0.gemfile
  - rvm: jruby-9.1.9.0
    gemfile: gemfiles/activerecord_6.0rc1.gemfile
  - rvm: jruby-9.2.5.0
    gemfile: gemfiles/activerecord_5.0.gemfile
  - rvm: jruby-9.2.5.0
    gemfile: gemfiles/activerecord_6.0rc1.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

before_install:
  #- gem update --system
  - gem install bundler
script:
  - bundle exec rake
